// <auto-generated />
using System;
using Backend_QLTE.ChildService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_QLTE.ChildService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ChildDbContext))]
    partial class ChildDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaXuLy")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiCanhBao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("AlertId");

                    b.HasIndex("ChildId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiTinNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.Child", b =>
                {
                    b.Property<Guid>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhomTuoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChildId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.DangerZone", b =>
                {
                    b.Property<Guid>("DangerZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BanKinh")
                        .HasColumnType("float");

                    b.Property<Guid?>("ChildrenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("KinhDo")
                        .HasColumnType("float");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ViDo")
                        .HasColumnType("float");

                    b.HasKey("DangerZoneId");

                    b.HasIndex("ChildrenId");

                    b.ToTable("DangerZones");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.DeviceInfo", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IMEI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTracking")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Pin")
                        .HasColumnType("int");

                    b.Property<string>("TenThietBi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThaiOnline")
                        .HasColumnType("bit");

                    b.HasKey("DeviceId");

                    b.HasIndex("ChildId")
                        .IsUnique();

                    b.ToTable("DeviceInfos");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.DeviceRestriction", b =>
                {
                    b.Property<Guid>("RestrictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowedDomains")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("BlockedApps")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BlockedDomains")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFirewallEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RestrictionId");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceRestrictions");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.ExamSchedule", b =>
                {
                    b.Property<Guid>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaThiXong")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MonThi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianThi")
                        .HasColumnType("datetime2");

                    b.HasKey("ExamId");

                    b.HasIndex("ChildId");

                    b.ToTable("ExamSchedules");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.LocationHistory", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("DoChinhXac")
                        .HasColumnType("float");

                    b.Property<double>("KinhDo")
                        .HasColumnType("float");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<double>("ViDo")
                        .HasColumnType("float");

                    b.HasKey("LocationId");

                    b.HasIndex("ChildId");

                    b.ToTable("LocationHistories");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.SOSRequest", b =>
                {
                    b.Property<Guid>("SOSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("KinhDo")
                        .HasColumnType("float");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ViDo")
                        .HasColumnType("float");

                    b.HasKey("SOSId");

                    b.HasIndex("ChildId");

                    b.ToTable("SOSRequests");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.SafeZone", b =>
                {
                    b.Property<Guid>("SafeZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BanKinh")
                        .HasColumnType("float");

                    b.Property<Guid?>("ChildrenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("KinhDo")
                        .HasColumnType("float");

                    b.Property<string>("TenZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ViDo")
                        .HasColumnType("float");

                    b.HasKey("SafeZoneId");

                    b.HasIndex("ChildrenId");

                    b.ToTable("SafeZones");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Thu")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ChildId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.StudyPeriod", b =>
                {
                    b.Property<Guid>("StudyPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("RepeatPattern")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("StudyPeriodId");

                    b.HasIndex("ChildId");

                    b.ToTable("StudyPeriods");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.Alert", b =>
                {
                    b.HasOne("Backend_QLTE.ChildService.Domain.Entities.Child", "Child")
                        .WithMany("Alerts")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.DangerZone", b =>
                {
                    b.HasOne("Backend_QLTE.ChildService.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildrenId");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.DeviceInfo", b =>
                {
                    b.HasOne("Backend_QLTE.ChildService.Domain.Entities.Child", "Child")
                        .WithOne("DeviceInfo")
                        .HasForeignKey("Backend_QLTE.ChildService.Domain.Entities.DeviceInfo", "ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.DeviceRestriction", b =>
                {
                    b.HasOne("Backend_QLTE.ChildService.Domain.Entities.DeviceInfo", "Device")
                        .WithMany("DeviceRestrictions")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.ExamSchedule", b =>
                {
                    b.HasOne("Backend_QLTE.ChildService.Domain.Entities.Child", "Child")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.LocationHistory", b =>
                {
                    b.HasOne("Backend_QLTE.ChildService.Domain.Entities.Child", "Child")
                        .WithMany("LocationHistories")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.SOSRequest", b =>
                {
                    b.HasOne("Backend_QLTE.ChildService.Domain.Entities.Child", "Child")
                        .WithMany("SOSRequests")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.SafeZone", b =>
                {
                    b.HasOne("Backend_QLTE.ChildService.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildrenId");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("Backend_QLTE.ChildService.Domain.Entities.Child", "Child")
                        .WithMany("Schedules")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.StudyPeriod", b =>
                {
                    b.HasOne("Backend_QLTE.ChildService.Domain.Entities.Child", "Child")
                        .WithMany("StudyPeriods")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.Child", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("DeviceInfo");

                    b.Navigation("ExamSchedules");

                    b.Navigation("LocationHistories");

                    b.Navigation("SOSRequests");

                    b.Navigation("Schedules");

                    b.Navigation("StudyPeriods");
                });

            modelBuilder.Entity("Backend_QLTE.ChildService.Domain.Entities.DeviceInfo", b =>
                {
                    b.Navigation("DeviceRestrictions");
                });
#pragma warning restore 612, 618
        }
    }
}
